[package]
name = "hp_portfolio"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "hp_portfolio_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1.0"
convert_case = "0.11.0"
prettyplease = "0.2"

[dependencies]
dto_traits = { path = "../dto_traits" }
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

sqlx = { version = "0.9", features = ["runtime-tokio", "sqlite", "macros", "chrono"] }
tokio = { version = "1", features = ["full"] }
polars = { version = "0.53.0", features = ["lazy", "csv"] }
dotenvy = "0.15.7"
chrono = { version = "0.4", features = ["serde"] } # use 0.4 to avoid conflicts with other deps
anyhow = "1.0.102"
tauri-plugin-dialog = "2.7.1"
convert_case = "0.11.0"
uuid = "1.23.1"
